### ISSUE TITLE
Return types in TypeScript declaration files are too narrow

### ISSUE THREAD

**Issue by DanielSWolf** [cospired/i18n-iso-languages#29]
According to *index.d.ts*, the function `getAlpha2Code` always returns a string. According to the unit tests, it returns a string on success, `undefined` otherwise.

The type definition should be changed to read

```ts
export function getAlpha2Code(name: string, lang: string): string | undefined;
```

I suspect that the same is true for most of the functions.

**Comment by e110c0** [comment]
MR would be welcome for this

**Comment by DanielSWolf** [comment]
I've created a PR.

**Comment by e110c0** [comment]
Thank you. PR merged and will be in the next release.
