### ISSUE TITLE
Improve German language names

### ISSUE THREAD

**Issue by DanielSWolf** [cospired/i18n-iso-languages#30]
The list of German language names (*langs/de.json*) contains a number of inaccuracies:

| Code | Current German name    | Proposed German name  |
|------|------------------------|-----------------------|
| 'az' | 'Aserbeidschanisch'    | 'Aserbaidschanisch'   |
| 'ht' | 'Haitien'              | 'Haitianisch'         |
| 'io' | 'Sinohoan'             | 'Ido'                 |
| 'ga' | 'Irish'                | 'Irisch'              |
| 'mk' | 'Makedonisch'          | 'Mazedonisch'         |
| 'na' | 'Nauruanisch'          | 'Nauruisch'           |
| 'gd' | 'Gälisch-Schottisch'   | 'Schottisch-Gälisch'  |
| 'th' | 'Thailändisch'         | 'Thai'                |

In addition, there are some entries that are technically correct, but do not represent the most common German name:

| Code | Current German name    | Proposed German name  |
|------|------------------------|-----------------------|
| 'id' | 'Bahasa Indonesia'     | 'Indonesisch'         |
| 'mi' | 'Maori-Sprache'        | 'Maori'               |
| 'pa' | 'Pandschabi-Sprache'   | 'Panjabi'             |
| 'st' | 'Süd-Sotho-Sprache'    | 'Sesotho'             |
| 'cy' | 'Kymrisch'             | 'Walisisch'           |

**Comment by e110c0** [comment]
full German file checked, and mostly followed the suggestions. Found even more stuff to adapt. @DanielSWolf please have a look if that resolves the issue

**Comment by DanielSWolf** [comment]
Thanks for making these changes! Regarding the two controversial cases:

* You have `th` as "Thailändisch", I have "Thai". It's my understanding that both are correct, so your version is fine by me.
* You have `pa` as "Pandjabi", I have "Panjabi". [According to Wikipedia](https://de.wikipedia.org/wiki/Panjabi), valid German spellings are "Panjabi" (mine, also main article title), "Punjabi", and "Pandschabi", but not "Pandjabi". Also, when searching for "Pandjabi", the German version of Google suggests "Panjabi" instead.

**Comment by DanielSWolf** [comment]
@e110c0 I would greatly appreciate if you could publish a new version containing the fixes! Until then, I need to maintain fallback logic for these cases in my own code.

**Comment by e110c0** [comment]
just released 2.2.0
 generally, you could also use `npm i git+https://github.com/cospired/i18n-iso-languages.git#<commit hash>` to use an unreleased version in your code
