### ISSUE TITLE
Shouldn't "Bihari languages" just be "Bihari"?

### ISSUE THREAD

**Issue by Boscop** [cospired/i18n-iso-languages#57]
Shouldn't the entry for "Bihari languages" just be "Bihari" in langs/en.json (i.e. singular instead of plural, like it is for the other [`langs/*.json`](https://github.com/search?q=repo%3Acospired%2Fi18n-iso-languages%20Bihari&type=code) files)?
https://github.com/cospired/i18n-iso-languages/blob/f2bdcfed1de981467b34f4e3c007b5523a5a1dca/langs/en.json#L19

**Comment by e110c0** [comment]
according to https://en.wikipedia.org/wiki/Bihari_languages it is a group of languages. the used name is also the official ISO639.
Even though the code `bh` is marked deprecated, we will keep it in the library until it is removed from ISO639-1
